name: 02 - Workflow events

on: 
    push:
    pull_request:
    schedule:
        - cron: '0 0 * * *' # every day at midnight
    workflow_dispatch:
        
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "I´ve been triggeres by a(n) ${{ github.event_name }} event."